name: MacOS Ventura Swift Release CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  exec-mac13-ci-release:
    runs-on: macos-13

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Release build
        run: swift build -c release

      - name: Release Test
        run: swift test -c release
