name: MacOS Ventura Swift Debug CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  exec-mac13-ci-debug:
    runs-on: macos-13

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Debug Build
        run: swift build -c debug

      - name: Debug Test
        run: swift test
